# Mental Health Predictions

This jupyter notebook will help us analyze anbd clean the data of our mental health sample.

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("playground-series-s4e11/sample_submission.csv")
df.sample(5)

           id  Depression
11280  151980           0
62441  203141           0
37238  177938           0
40013  180713           0
52195  192895           0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 93800 entries, 0 to 93799
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          93800 non-null  int64
 1   Depression  93800 non-null  int64
dtypes: int64(2)
memory usage: 1.4 MB

In [9]:
sample = pd.read_csv("playground-series-s4e11/test.csv")
sample.info()

<class 'pandas.DataFrame'>
RangeIndex: 93800 entries, 0 to 93799
Data columns (total 19 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     93800 non-null  int64
 1   Name                                   93800 non-null  str
 2   Gender                                 93800 non-null  str
 3   Age                                    93800 non-null  float64
 4   City                                   93800 non-null  str
 5   Working Professional or Student        93800 non-null  str
 6   Profession                             69168 non-null  str
 7   Academic Pressure                      18767 non-null  float64
 8   Work Pressure                          75022 non-null  float64
 9   CGPA                                   18766 non-null  float64
 10  Study Satisfaction                     18767 non-null  float64
 11  Job Satisfaction                       75026 non-null  float64
 12  Sleep Duration                         93800 non-null  str
 13  Dietary Habits                         93795 non-null  str
 14  Degree                                 93798 non-null  str
 15  Have you ever had suicidal thoughts ?  93800 non-null  str
 16  Work/Study Hours                       93800 non-null  float64
 17  Financial Stress                       93800 non-null  float64
 18  Family History of Mental Illness       93800 non-null  str
dtypes: float64(8), int64(1), str(10)
memory usage: 13.6 MB

As we can see we have some columns that have many missing values, such as academic pressure and job satisfaction, etc. These values are not missing at random, as they depend on other variables such as working profssional or student.

In [10]:
sample.head()

,id,Name,Gender,Age,City,Working Professional or Student,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness
0,140700,Shivam,Male,53.0,Visakhapatnam,Working Professional,Judge,NaN,2.0,NaN,NaN,5.0,Less than 5 hours,Moderate,LLB,No,9.0,3.0,Yes
1,140701,Sanya,Female,58.0,Kolkata,Working Professional,Educational Consultant,NaN,2.0,NaN,NaN,4.0,Less than 5 hours,Moderate,B.Ed,No,6.0,4.0,No
2,140702,Yash,Male,53.0,Jaipur,Working Professional,Teacher,NaN,4.0,NaN,NaN,1.0,7-8 hours,Moderate,B.Arch,Yes,12.0,4.0,No
3,140703,Nalini,Female,23.0,Rajkot,Student,NaN,5.0,NaN,6.84,1.0,NaN,More than 8 hours,Moderate,BSc,Yes,10.0,4.0,No
4,140704,Shaurya,Male,47.0,Kalyan,Working Professional,Teacher,NaN,5.0,NaN,NaN,5.0,7-8 hours,Moderate,BCA,Yes,3.0,4.0,No

In [ ]:
format(sample.duplicated().sum()))